#!/bin/sh

# Autostart
~/.fehbg &
conky &
numlockx &
setxkbmap -layout us,ru && setxkbmap -option 'grp:alt_shift_toggle' &
~/.config/polybar/launch.sh &
udiskie &
sxhkd &
light-locker --no-late-locking --lock-on-suspend &
compton -bC --config ~/.config/compton/compton.conf &

bspc monitor -d I II III IV V VI VII VIII IX X

BW=2
bspc config border_width $BW
bspc config window_gap -$BW
bspc config top_padding 29.5
for side in right bottom left ; do
	bspc config ${side}_padding $BW
done

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Code desktop='^1'
bspc rule -a Chromium desktop='^2'
bspc rule -a TelegramDesktop desktop='^3'
